/* Generated by Yosys 0.34 (git sha1 4a1b5599258, gcc 8.3.1 -fPIC -Os) */

module andor(a, b, c, clk, rst, out, out2);
  wire _0_;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input clk;
  wire clk;
  output out;
  wire out;
  output out2;
  wire out2;
  input rst;
  wire rst;
  sky130_fd_sc_hd__a21o_2 _1_ (
    .A1(b),
    .A2(out),
    .B1(c),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfrtp_2 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(out2),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_2 _3_ (
    .CLK(clk),
    .D(a),
    .Q(out),
    .RESET_B(rst)
  );
endmodule