/* Generated by Yosys 0.34 (git sha1 4a1b5599258, gcc 8.3.1 -fPIC -Os) */

module ClkDiv(i_ref_clk, i_rst_n, i_clk_en, i_div_ratio, o_div_clk);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire \counter[0] ;
  wire \counter[1] ;
  wire \counter[2] ;
  wire flag;
  input i_clk_en;
  wire i_clk_en;
  input [2:0] i_div_ratio;
  wire [2:0] i_div_ratio;
  input i_ref_clk;
  wire i_ref_clk;
  input i_rst_n;
  wire i_rst_n;
  output o_div_clk;
  wire o_div_clk;
  sky130_fd_sc_hd__and2b_2 _26_ (
    .A_N(i_div_ratio[1]),
    .B(\counter[0] ),
    .X(_05_)
  );
  sky130_fd_sc_hd__and2b_2 _27_ (
    .A_N(\counter[0] ),
    .B(i_div_ratio[1]),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_2 _28_ (
    .A(i_div_ratio[2]),
    .B(\counter[1] ),
    .Y(_07_)
  );
  sky130_fd_sc_hd__mux2_2 _29_ (
    .A0(_05_),
    .A1(_06_),
    .S(_07_),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2_2 _30_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xor2_2 _31_ (
    .A(\counter[2] ),
    .B(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__and4_2 _32_ (
    .A(i_div_ratio[0]),
    .B(flag),
    .C(_08_),
    .D(_10_),
    .X(_11_)
  );
  sky130_fd_sc_hd__or4b_2 _33_ (
    .A(\counter[2] ),
    .B(flag),
    .C(_06_),
    .D_N(i_div_ratio[0]),
    .X(_12_)
  );
  sky130_fd_sc_hd__nor3b_2 _34_ (
    .A(_05_),
    .B(_12_),
    .C_N(_07_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__or2_2 _35_ (
    .A(i_div_ratio[2]),
    .B(i_div_ratio[1]),
    .X(_14_)
  );
  sky130_fd_sc_hd__or4bb_2 _36_ (
    .A(i_div_ratio[0]),
    .B(\counter[2] ),
    .C_N(_08_),
    .D_N(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__and2_2 _37_ (
    .A(i_clk_en),
    .B(_14_),
    .X(_16_)
  );
  sky130_fd_sc_hd__o211a_2 _38_ (
    .A1(_11_),
    .A2(_13_),
    .B1(_15_),
    .C1(_16_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xor2_2 _39_ (
    .A(flag),
    .B(_17_),
    .X(_00_)
  );
  sky130_fd_sc_hd__and4bb_2 _40_ (
    .A_N(i_div_ratio[0]),
    .B_N(\counter[2] ),
    .C(_08_),
    .D(_14_),
    .X(_18_)
  );
  sky130_fd_sc_hd__o31a_2 _41_ (
    .A1(_18_),
    .A2(_11_),
    .A3(_13_),
    .B1(_16_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xor2_2 _42_ (
    .A(o_div_clk),
    .B(_19_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand2_2 _43_ (
    .A(\counter[0] ),
    .B(_16_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__or2_2 _44_ (
    .A(\counter[0] ),
    .B(_16_),
    .X(_21_)
  );
  sky130_fd_sc_hd__and3b_2 _45_ (
    .A_N(_19_),
    .B(_20_),
    .C(_21_),
    .X(_22_)
  );
  sky130_fd_sc_hd__buf_1 _46_ (
    .A(_22_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xor2_2 _47_ (
    .A(\counter[1] ),
    .B(_20_),
    .X(_23_)
  );
  sky130_fd_sc_hd__nor2_2 _48_ (
    .A(_19_),
    .B(_23_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_2 _49_ (
    .A(_10_),
    .B(_13_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__mux2_2 _50_ (
    .A0(\counter[2] ),
    .A1(_24_),
    .S(_16_),
    .X(_25_)
  );
  sky130_fd_sc_hd__buf_1 _51_ (
    .A(_25_),
    .X(_04_)
  );
  sky130_fd_sc_hd__dfrtp_2 _52_ (
    .CLK(i_ref_clk),
    .D(_00_),
    .Q(flag),
    .RESET_B(i_rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _53_ (
    .CLK(i_ref_clk),
    .D(_01_),
    .Q(o_div_clk),
    .RESET_B(i_rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _54_ (
    .CLK(i_ref_clk),
    .D(_02_),
    .Q(\counter[0] ),
    .RESET_B(i_rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _55_ (
    .CLK(i_ref_clk),
    .D(_03_),
    .Q(\counter[1] ),
    .RESET_B(i_rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _56_ (
    .CLK(i_ref_clk),
    .D(_04_),
    .Q(\counter[2] ),
    .RESET_B(i_rst_n)
  );
endmodule
